#!/usr/bin/sh

zeal60 backlight_config_set_values \
use_split_backspace=1 \
use_split_left_shift=0 \
use_split_right_shift=1 \
use_7u_spacebar=0 \
use_iso_enter=0 \
disable_when_usb_suspended=1 \
disable_after_timeout=10

zeal60 colors \
ROW0=hsv\(260,100,100\) \
ROW1=hsv\(270,95,100\) \
ROW2=hsv\(280,90,100\) \
ROW3=hsv\(290,85,100\) \
ROW4=hsv\(300,80,100\) \
MODS=hsv\(180,100,100\) \
WASD=hsv\(0,100,100\) \
UNUSED=hsv\(0,0,0\) \
PORTAL1=hsv\(200,100,100\) \
PORTAL2=hsv\(30,100,100\) \
MODS     ROW0     ROW0     ROW0     ROW0     ROW0     ROW0     ROW0     ROW0     ROW0     ROW0     ROW0     ROW0     ROW0    \
MODS     ROW1     WASD     ROW1     ROW1     ROW1     ROW1     ROW1     ROW1     ROW1     ROW1     ROW1     ROW1     MODS    \
MODS     WASD     WASD     WASD     ROW2     ROW2     ROW2     ROW2     ROW2     ROW2     ROW2     ROW2     MODS     ROW0    \
MODS     MODS     ROW3     ROW3     ROW3     ROW3     ROW3     ROW3     ROW3     ROW3     ROW3     ROW3     MODS     MODS    \
MODS     MODS     PORTAL2  ROW4     UNUSED   UNUSED   UNUSED   ROW4     UNUSED   ROW4     PORTAL1  MODS     MODS     MODS

zeal60 keymap 0 \
KC_ESC   KC_1     KC_2     KC_3     KC_4     KC_5     KC_6     KC_7     KC_8     KC_9     KC_0     KC_MINS  KC_EQL   KC_BSLS \
KC_TAB   KC_Q     KC_W     KC_E     KC_R     KC_T     KC_Y     KC_U     KC_I     KC_O     KC_P     KC_LBRC  KC_RBRC  KC_BSPC \
FN_MO13  KC_A     KC_S     KC_D     KC_F     KC_G     KC_H     KC_J     KC_K     KC_L     KC_SCLN  KC_QUOT  KC_ENT   KC_GRV  \
KC_LSFT  KC_NO    KC_Z     KC_X     KC_C     KC_V     KC_B     KC_N     KC_M     KC_COMM  KC_DOT   KC_SLSH  MT\(MOD_RSFT,KC_UP\)  FN_MO13 \
KC_LCTL  KC_LALT  KC_LGUI  KC_NO    KC_NO    KC_NO    KC_NO    KC_SPC   KC_NO    KC_NO    FN_MO23  MT\(MOD_RALT,KC_LEFT\) MT\(MOD_RGUI,KC_DOWN\)  MT\(MOD_RCTL,KC_RIGHT\)

zeal60 keymap 1 \
KC_TILD  KC_F1    KC_F2    KC_F3    KC_F4    KC_F5    KC_F6    KC_F7    KC_F8    KC_F9    KC_F10   KC_F11   KC_F12   KC_INS \
KC_TRNS  KC_TRNS  KC_UP    KC_TRNS  KC_TRNS  KC_TRNS  KC_HOME  KC_PGDN  KC_PGUP  KC_END   KC_TRNS  KC_TRNS  KC_TRNS  KC_DEL \
KC_TRNS  KC_LEFT  KC_DOWN  KC_RIGHT KC_TRNS  KC_TRNS  KC_LEFT  KC_DOWN  KC_UP    KC_RIGHT KC_TRNS  KC_TRNS  KC_TRNS  KC_PSCR \
KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_UP  KC_TRNS \
KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_LEFT  KC_DOWN  KC_RIGHT

zeal60 keymap 2 \
KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_MUTE  KC_VOLD \
KC_TRNS  KC_TRNS  KC_UP    KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS \
KC_TRNS  KC_LEFT  KC_DOWN  KC_RGHT  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_VOLU \
KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_CALC  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS \
KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS

zeal60 keymap 3 \
RESET    EF_DEC   EF_INC   H1_DEC   H1_INC   H2_DEC   H2_INC   KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  BR_DEC   BR_INC   KC_TRNS \
KC_TRNS  KC_TRNS  KC_TRNS  S1_DEC   S1_INC   S2_DEC   S2_INC   KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS \
KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS \
KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  TG_NKRO  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS \
KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS  KC_TRNS
