#pragma once

#ifdef ZEAL65

#define DEVICE_VID 0x5A45
#define DEVICE_PID 0x0065
#define DEVICE_INTERFACE_NUMBER 0x01

#define RAW_HID_BUFFER_SIZE 32

#define MATRIX_COLS 15
#define MATRIX_ROWS 5

#else

#define DEVICE_VID 0x6582
#define DEVICE_PID 0x0028
#define DEVICE_INTERFACE_NUMBER 0x01

#define RAW_HID_BUFFER_SIZE 32

#define MATRIX_COLS 14
#define MATRIX_ROWS 5

#endif